site_name: Francesco Franco Classes
site_url: https://hyperfra.github.io/
theme:
  name: material
  features:
    - content.code.annotate
plugins:
  - search
  - mermaid2:
      version: 9.1.7
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mermaid.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css